version: "3.3"

services:
  api:
    image: snek-at/ami-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/:/api/
    command: bash -c "while !</dev/tcp/api_db/5432; do sleep 1; done; uvicorn api.app:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    depends_on:
      - api_db
    restart: on-failure # workaround for dependency issue to api_db
    environment:
      - DB_USER=api_db
      - DB_PASSWORD=api_db
      - DB_HOST=api_db
      - DB_PORT=5432
      - DB_NAME=api_db
      - ACCEPTED_TO_EMAILS=${ACCEPTED_TO_EMAILS}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
  api_db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=api_db
      - POSTGRES_PASSWORD=api_db
      - POSTGRES_DB=api_db

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SESSION_COOKIE_SAMESITE: "None"
      PGADMIN_CONFIG_SESSION_COOKIE_SECURE: "True"
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
    ports:
      - "5050:80"

volumes:
  postgres_data:
