version: '3.7'

services:
    gateway:
        image: ami/k-api-gateway:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./gateway
            dockerfile: Dockerfile
        env_file:
            - ./gateway/.env
        ports:
          - 8001:8000
        depends_on:
          - users
          - orders
        volumes:
          - ./gateway:/app

    users:
        image: ami/k-users:latest
        command: sh -c "while !</dev/tcp/db/5431; do sleep 1; done; uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./users
            dockerfile: Dockerfile
        environment:
            - DATABASE_URL=postgresql://fastapi_users_db:fastapi_users_db@db:5431/fastapi_users_db
        env_file:
            - ./users/.env
        volumes:
          - ./users:/app
        depends_on:
            - users_db

    users_db:
        image: postgres:13-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        expose:
            - 5431
        environment:
            - POSTGRES_USER=fastapi_users_db
            - POSTGRES_PASSWORD=fastapi_users_db
            - POSTGRES_DB=fastapi_users_db

    orders:
        image: ami/k-orders:latest
        command: sh -c "while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./orders
            dockerfile: Dockerfile
        env_file:
            - ./orders/.env
        environment:
            - DATABASE_URL=postgresql://fastapi_orders_db:fastapi_orders_db@db:5432/fastapi_orders_db
        volumes:
          - ./orders:/app
        depends_on:
            - orders_db

    orders_db:
        image: postgres:13-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        expose:
            - 5432
        environment:
            - POSTGRES_USER=fastapi_orders_db
            - POSTGRES_PASSWORD=fastapi_orders_db
            - POSTGRES_DB=fastapi_orders_db

volumes:
    postgres_data:
